### ISSUE TITLE
Add support for the Trigger API on custom page fields {variable}

### ISSUE THREAD

**Issue by jeremymouton** [rainlab/pages-plugin#236]
In YML and PHP, we can define a trigger by doing this:

```yml
my_field:
  label: Link
  span: right
  trigger:
     action: show
     field: my_other_field
     condition: checked
```

Is there a way to pass a trigger to a custom form element?

Such as 

```
{variable
  name="my_field"
  label="Link"
  trigger-action="show"
  trigger-field="my_other_field"
  trigger-condition="checked"
  span="right"}
{/variable}
```
