### ISSUE TITLE
Option to show overview of subpages on parent page

### ISSUE THREAD

**Issue by maartenmachiels** [rainlab/pages-plugin#273]
Hi, I've been happily using the static pages plugin and am loving it. I currently have a menu that has one sublevel.

```
Home
Overview
- Subpage A
- Subpage B
- Subpage C
Contact
```

The subpages show up in the main menu as expected. But I'd like to go a step further show the 3 subpages as 3 links on the (parent) overview page. This way, if the user clicks on Overview in the main menu, they will find a nice layout with 3 links, each one representing a subpage.

Important would be to be able to access the name, url, and custom fields (variables / placeholders) of the subpages, so I can show an image (it's in a variable of the subpage) and a label per page. 

Someone has created a plugin to do exactly this, but it does not seem to be maintained or working anymore: [https://octobercms.com/plugin/jwilson8767-subpages](url)

Other people have been posting possible solutions aswel, but I cannot find a practical example:

- [https://octobercms.com/forum/post/render-the-content-of-subpages](url)
- [https://octobercms.inetis.ch/render-content-subpages](url)

Might you have any views on wether this is possible and how to proceed? Thanks in advance.

**Comment by jan-vince** [comment]
You can list all Static pages and then traverse through children.

Like this:

````php
title = "Pages"
url = "/pages"
layout = "default"
is_hidden = 0

==
<?php

function onStart() {

    $theme = Cms\Classes\Theme::getEditTheme();
    $pageList = new RainLab\Pages\Classes\PageList($theme);

    $this['pagesList'] = $pageList->listPages();

}

?>
==

{% for page in pagesList if page.parent is empty %}

    <h1>{{ page.title }}</h1>

    {% for subpage in page.children %}

        <h2>* {{ subpage.title }}</h2>

    {% endfor %}


{% endfor %}
````

*You can create macro if you want recursion. For one level deep this is ok, I think :)*

**Comment by maartenmachiels** [comment]
Hi @jan-vince , thanks so much for your quick answer. Nice to know it's possible. 
I've entered this code into the layout my static page uses. The problem is that this code outputs all pages, regardless of their level (pages and subpages are displayed randomly). Could something be wrong with my setup?

**Comment by jan-vince** [comment]
The PHP code above gets all pages and first Twig ````{% for %}```` loop filters only top level pages.

I have tested it and it works for me.

Are you sure you have created sub-pages? Can you post ````meta/static-pages.yaml``` file content (or fragment if too long).

*There is a button Add subpage when you hover page in pages list (in administration).*

**Comment by maartenmachiels** [comment]
Hi,

Yes, here's what's happening in `meta/static-pages.yaml`

```
static-pages:
    index: {  }
    about-us: {  }
    operations: {  }
    sustainability: {  }
    news: {  }
    contact: {  }
    work-rosy-blue: {  }
    rough-trading: {  }
    diamond-manufaturing: {  }
    polished-trading: {  }
```
No structure here, but in the folder `meta/menus/hoofdmenu.yaml`

```
name: Hoofdmenu
items:
    -
        title: Home
        nesting: '0'
        type: static-page
        url: ''
        code: ''
        reference: index
        cmsPage: ''
        replace: '0'
        viewBag:
            isHidden: '0'
            cssClass: ''
            isExternal: '0'
    -
        title: Operations
        nesting: '1'
        type: static-page
        code: ''
        reference: operations
        replace: '0'
        viewBag:
            isHidden: '0'
            cssClass: ''
            isExternal: '0'
        items:
            -
                title: 'Rough Trading'
                nesting: '0'
                type: static-page
                url: ''
                code: ''
                reference: rough-trading
                cmsPage: ''
                replace: '0'
                viewBag:
                    isHidden: '1'
                    cssClass: ''
                    isExternal: '0'
            -
                title: 'Diamond Manufacturing'
                nesting: '0'
                type: static-page
                url: ''
                code: ''
                reference: diamond-manufaturing
                cmsPage: ''
                replace: '0'
                viewBag:
                    isHidden: '1'
                    cssClass: ''
                    isExternal: '0'
            -
                title: 'Polished Trading'
                nesting: '0'
                type: static-page
                url: ''
                code: ''
                reference: polished-trading
                cmsPage: ''
                replace: '0'
                viewBag:
                    isHidden: '1'
                    cssClass: ''
                    isExternal: '0'
    -
        title: 'About us'
        nesting: '0'
        type: static-page
        url: ''
        code: ''
        reference: about-us
        cmsPage: ''
        replace: '0'
        viewBag:
            isHidden: '0'
            cssClass: ''
            isExternal: '0'
    -
        title: Logo
        nesting: '0'
        type: static-page
        url: ''
        code: ''
        reference: index
        cmsPage: ''
        replace: '0'
        viewBag:
            isHidden: '0'
            cssClass: c-logo
            isExternal: '0'
    -
        title: News
        nesting: '0'
        type: static-page
        url: ''
        code: ''
        reference: news
        cmsPage: ''
        replace: '0'
        viewBag:
            isHidden: '0'
            cssClass: ''
            isExternal: '0'
    -
        title: Sustainability
        nesting: '0'
        type: static-page
        url: ''
        code: ''
        reference: sustainability
        cmsPage: ''
        replace: '0'
        viewBag:
            isHidden: '0'
            cssClass: ''
            isExternal: '0'
    -
        title: Contact
        nesting: '0'
        type: static-page
        url: ''
        code: ''
        reference: contact
        cmsPage: ''
        replace: '0'
        viewBag:
            isHidden: '0'
            cssClass: ''
            isExternal: '0'
```
Screenshot of my menu "hoofdmenu" (my main menu):
![menu](https://user-images.githubusercontent.com/3584586/28366542-7825d932-6c8d-11e7-98be-445b039358e3.PNG)

What do you think might be wrong?

**Comment by maartenmachiels** [comment]
I've modified `meta/static-pages.yaml` and now I see again all pages, but with the subpages in the right spot:

```
static-pages:
    index: {  }
    about-us: {  }
    operations:
      rough-trading: {  }
      diamond-manufaturing: {  }
      polished-trading: {  }
    sustainability: {  }
    news: {  }
    contact: {  }
    work-rosy-blue: {  }
```
I'm guessing that maybe there was an issue with generating this file when dragging and dropping?
I'd love to have a filter of the subpages of the current page only.  How can I modify the loop so that only the children of the current page are taken into account?

Thanks for all your help, I really appreciate it.
