### ISSUE TITLE
Support for modelClass in groups of syntax fields?

### ISSUE THREAD

**Issue by zlobec** [rainlab/pages-plugin#340]
I've been trying to include a modelClass in the groups yaml file, but I always get the error:
`The model class RainLab\Pages\Classes\Page must define a method nameOfMethod()`
No matter what modelClass i put in...

Is this a bug or not a feature at all?
Regard,
Darjan

**Comment by LukeTowers** [comment]
@zlobec please post the configuration you are attempting to use, recordfinders aren't supported because they currently rely on relations defined on the model directly to work correctly.

**Comment by zlobec** [comment]
The idea was to use the modelClass to get records from a plugin model:

```
galleryFull:
  name: Gallery Full
  description: Gallery full loader listing for Static page
  icon: icon-camera-retro
  fields:
    section:
      label: Gallery Full
      type: section
    property:
      modelClass: Acme\Blog\Models\Category
      conditions: category_id in (:filtered)
      nameFrom: name
```
Seems like it doesn't want any models outside the Static Pages controllers.
Regard,
Darjan

**Comment by LukeTowers** [comment]
@zlobec where are you using that YAML config? I don't recognize the context at all.

**Comment by zlobec** [comment]
@LukeTowers I'm using it a groups YAML file in a variable repeater as instructed [here](https://octobercms.com/forum/post/nested-repeater-fields-on-static-pages).

**Comment by LukeTowers** [comment]
@zlobec what is the purpose of
```yaml
property:
      modelClass: Acme\Blog\Models\Category
      conditions: category_id in (:filtered)
      nameFrom: name
```
?

That looks like a filter definition, not a field definition.
