### ISSUE TITLE
Undefined Index on Line 114 plugins/rainlab/pages/formwidgets/MenuItems.php

### ISSUE THREAD

**Issue by KirbyFox** [rainlab/pages-plugin#346]
Can no longer access navigation links via CMS

"Undefined index: " on line 114 of plugins/rainlab/pages/formwidgets/MenuItems.php

Checked YAML file against validator and it's valid.

**Comment by LukeTowers** [comment]
@KirbyFox please post YAML file, looks like $item->type is null in your case

**Comment by recallfuture** [comment]
I met this problem, too, so I backup a yaml file which is fine, but only I save the menu in Page->menus, the yaml file will lose a few of last lines, like type, and all item has added "nesting: ''" and "replace: ''" in yaml file

**Comment by recallfuture** [comment]
This is my yaml file which is fine, I'll show the last of lines
```
    -
        title: something
        type: url
        url: /
        code: ''
        viewBag:
            isHidden: '0'
            cssClass: ''
            isExternal: '0'
        items:
            -
                title: something
                type: url
                url: /
                code: ''
                viewBag:
                    isHidden: '0'
                    cssClass: ''
                    isExternal: '0'
            -
                title: something
                type: url
                url: /
                code: ''
                viewBag:
                    isHidden: '0'
                    cssClass: ''
                    isExternal: '0'
            -
                title: something
                type: url
                url: /
                code: ''
                viewBag:
                    isHidden: '0'
                    cssClass: ''
                    isExternal: '0'
    -
        title: something
        type: blog-post
        code: ''
        reference: '117'
        cmsPage: nav/index
        viewBag:
            isHidden: '0'
            cssClass: ''
            isExternal: '0'
    -
        title: something
        type: blog-post
        code: ''
        reference: '16'
        cmsPage: nav/index
        viewBag:
            isHidden: '0'
            cssClass: ''
            isExternal: '0'
```

**Comment by recallfuture** [comment]
But when I save in Page->Menus, every item changed, and I lose two of the last items
```
    -
        title: something
        nesting: ''
        type: url
        url: /
        code: ''
        reference: ''
        cmsPage: ''
        replace: ''
        viewBag:
            isHidden: '0'
            cssClass: ''
            isExternal: '0'
        items:
            -
                title: something
                nesting: ''
                type: url
                url: /
                code: ''
                reference: ''
                cmsPage: ''
                replace: ''
                viewBag:
                    isHidden: '0'
                    cssClass: ''
                    isExternal: '0'
            -
                title: something
                nesting: ''
                type: url
                url: /
                code: ''
                reference: ''
                cmsPage: ''
                replace: ''
                viewBag:
                    isHidden: '0'
                    cssClass: ''
                    isExternal: '0'
            -
                title: something
//end of file
```
