### ISSUE TITLE
After update 1.3.1 Allow nested items isn't working anymore

### ISSUE THREAD

**Issue by GameBurrow** [rainlab/pages-plugin#415]
After update 1.3.1 Allow nested items isn't working anymore. They just don't display in the menu anymore.

![image](https://user-images.githubusercontent.com/4341091/65895740-9da58680-e3b4-11e9-9d78-7e7c29237fe1.png)

**Comment by LukeTowers** [comment]
@GameBurrow are you using Database Templates?

**Comment by GameBurrow** [comment]
> @GameBurrow are you using Database Templates?

Not sure what you mean with that honestly, if it's something out of ordinary then no. I have pretty basic OctoberCMS setup.

I have following extensions:
![image](https://user-images.githubusercontent.com/4341091/65911814-dbff6d80-e3d5-11e9-973a-86727a334e72.png)

I haven't done any code alterations. Even the menu codes in partials are almost like they shipped with.

Here's my menu structure:
https://i.imgur.com/IzVbZj9.gifv

Pages nesting structure:
![image](https://user-images.githubusercontent.com/4341091/65912332-b3c43e80-e3d6-11e9-9291-329a06a89474.png)

This is how it looks live (now):
![image](https://user-images.githubusercontent.com/4341091/65912285-9db67e00-e3d6-11e9-9779-5c609935f1ae.png)

Here's one of the navbar codes also:
```
<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-dark fixed-top scrolling-navbar">

    <!-- Navbar brand -->
    <a class="navbar-brand" href="/"><img src="/storage/app/media/Logos/GroupFullWide2000px.png" width="300px"/></a>

    <!-- Collapse button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>

    <!-- Collapsible content -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <!-- Links -->
        <ul class="navbar-nav mr-auto">
            {% if staticMenu.menuItems %}
                {% set items = staticMenu.menuItems %}
                {% for item in items %}
                    <li class="nav-item {{ item.isActive or item.isChildActive ? 'active' : '' }}
                        {{ item.items ? 'dropdown btn-group' : '' }}"
                    >
                        <a class="nav-link {% if item.items %}'dropdown-toggle' {% endif %}"
                                {% if item.items %} id="dropdownMenu{{ item.title|replace({' ':'-'}) }}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"{% endif %}
                           href="{{ item.url }}"
                        >
                            {{ item.title }}
    
                            {% if item.items %}<span class="sr-only">(current)</span>{% endif %}
                        </a>
    
                        {% if item.items %}
                            <div class="dropdown-menu dropdown" aria-labelledby="dropdownMenu{{ item.title|replace({' ':'-'}) }}">
                                {% for child in item.items %}
                                    <a class="dropdown-item" href="{{ child.url }}">{{ child.title }}</a>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </li>
                {% endfor %}
            {% endif %}
        </ul>
        <!-- Links -->
        
        <ul class="navbar-nav ml-auto nav-flex-icons">
            <li class="nav-item">
                <a href="/discord" class="nav-link waves-effect waves-light">
                    <i class="fab fa-discord"></i>
                </a>
            </li>
            <li class="nav-item">
                <a href="https://www.facebook.com/GoBusVirtual/" class="nav-link waves-effect waves-light">
                    <i class="fab fa-facebook-f"></i>
                </a>
            </li>
            <li class="nav-item">
                <a href="https://steamcommunity.com/groups/gogroupvirtual" class="nav-link waves-effect waves-light">
                    <i class="fab fa-steam"></i>
                </a>
            </li>
            <li class="nav-item">
                <a href="https://wiki.gogroupvirtual.eu/" class="nav-link waves-effect waves-light">
                    <i class="fab fa-wikipedia-w"></i>
                </a>
            </li>
            <li class="nav-item">
                <a href="https://forum.gogroupvirtual.eu/" class="nav-link waves-effect waves-light">
                    <i class="far fa-comments"></i>
                </a>
            </li>
        </ul>

        <!-- Search form -->
        <form class="form-inline">
            <!--<input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">-->
        </form>
    </div>
    <!-- Collapsible content -->

</nav>
<!--/.Navbar-->
```
![image](https://user-images.githubusercontent.com/4341091/65912519-030a6f00-e3d7-11e9-8395-b7600dc59ca2.png)


So yeah all of this used to work and I haven't done anything else than ran update.

**Comment by LukeTowers** [comment]
Could you add the contents of your theme/meta/menus/main-menu.yaml file?

**Comment by GameBurrow** [comment]
```
name: MainMenu
items:
    -
        title: News
        nesting: ''
        type: cms-page
        url: ''
        code: ''
        reference: news
        cmsPage: ''
        replace: ''
        viewBag:
            isHidden: '0'
            cssClass: ''
            isExternal: '0'
    -
        title: About
        nesting: '0'
        type: static-page
        url: ''
        code: ''
        reference: about
        cmsPage: ''
        replace: '0'
        viewBag:
            isHidden: '0'
            cssClass: ''
            isExternal: '0'
    -
        title: Team
        nesting: '0'
        type: static-page
        url: ''
        code: ''
        reference: team
        cmsPage: ''
        replace: '0'
        viewBag:
            isHidden: '0'
            cssClass: ''
            isExternal: '0'
    -
        title: Rules
        nesting: '0'
        type: static-page
        url: ''
        code: ''
        reference: rules
        cmsPage: ''
        replace: '0'
        viewBag:
            isHidden: '0'
            cssClass: ''
            isExternal: '0'
    -
        title: 'OMSI 2'
        nesting: '0'
        type: static-page
        url: ''
        code: ''
        reference: omsi
        cmsPage: ''
        replace: '0'
        viewBag:
            isHidden: '0'
            cssClass: ''
            isExternal: '0'
        items:
            -
                title: 'OMSI 2'
                nesting: '1'
                type: static-page
                url: ''
                code: ''
                reference: omsi
                cmsPage: ''
                replace: '1'
                viewBag:
                    isHidden: '0'
                    cssClass: ''
                    isExternal: '0'
            -
                title: Maps
                nesting: ''
                type: cms-page
                url: ''
                code: ''
                reference: maps
                cmsPage: ''
                replace: ''
                viewBag:
                    isHidden: '0'
                    cssClass: ''
                    isExternal: '0'
            -
                title: Buses
                nesting: ''
                type: cms-page
                url: ''
                code: ''
                reference: buses
                cmsPage: ''
                replace: ''
                viewBag:
                    isHidden: '0'
                    cssClass: ''
                    isExternal: '0'
    -
        title: 'ATS & ETS 2'
        nesting: '1'
        type: static-page
        code: ''
        reference: haulage
        replace: '0'
        viewBag:
            isHidden: '0'
            cssClass: ''
            isExternal: '0'
    -
        title: LOTUS
        nesting: '0'
        type: static-page
        url: ''
        code: ''
        reference: lotus
        cmsPage: ''
        replace: '0'
        viewBag:
            isHidden: '0'
            cssClass: ''
            isExternal: '0'
    -
        title: Forum
        nesting: ''
        type: url
        url: 'https://forum.gogroupvirtual.eu'
        code: ''
        reference: ''
        cmsPage: ''
        replace: ''
        viewBag:
            isHidden: '0'
            cssClass: ''
            isExternal: '1'
    -
        title: Discord
        nesting: ''
        type: url
        url: 'https://gogroupvirtual.eu/discord'
        code: ''
        reference: ''
        cmsPage: ''
        replace: ''
        viewBag:
            isHidden: '0'
            cssClass: ''
            isExternal: '1'
    -
        title: Wiki
        nesting: ''
        type: url
        url: 'https://wiki.gogroupvirtual.eu'
        code: ''
        reference: ''
        cmsPage: ''
        replace: ''
        viewBag:
            isHidden: '0'
            cssClass: ''
            isExternal: '1'
    -
        title: Social
        nesting: ''
        type: header
        url: ''
        code: ''
        reference: ''
        cmsPage: ''
        replace: ''
        viewBag:
            isHidden: '0'
            cssClass: ''
            isExternal: '0'
        items:
            -
                title: 'Facebook page'
                nesting: ''
                type: url
                url: 'https://www.facebook.com/GoBusVirtual/'
                code: ''
                reference: ''
                cmsPage: ''
                replace: ''
                viewBag:
                    isHidden: '0'
                    cssClass: ''
                    isExternal: '1'
            -
                title: 'Steam Group'
                nesting: ''
                type: url
                url: 'https://steamcommunity.com/groups/gogroupvirtual'
                code: ''
                reference: ''
                cmsPage: ''
                replace: ''
                viewBag:
                    isHidden: '0'
                    cssClass: ''
                    isExternal: '1'

```

**Comment by bennothommo** [comment]
@GameBurrow would you mind also providing us with the content of your `meta/static-pages.yaml` file and the code that you use to generate the navigation, if possible?

**Comment by GameBurrow** [comment]
### static-pages.yaml
```
static-pages:
    index: {  }
    team: {  }
    omsi:
        omsi-about: {  }
        omsi-join-us: {  }
        omsi-extra-mods:
            omsi-extra-mods-install-kplus-julian-o405gn2: {  }
            omsi-extra-mods-install-kplus-7900: {  }
            omsi-extra-mods-install-kplus-man-lc-bremen-nord: {  }
            omsi-extra-mods-install-kplus-citaro-c2g: {  }
            omsi-extra-mods-install-kplus-su-iv: {  }
            omsi-extra-mods-install-k-iveco-crossway-le: {  }
        omsi-depot-files: {  }
        omsi-fleet-download: {  }
    haulage:
        haulage-about-new: {  }
        haulage-logit: {  }
    rules: {  }
    about: {  }
    lotus: {  }
```
Not sure, where I can find the last one?
