### ISSUE TITLE
Group descriptions are cutoff when using repeater groups

### ISSUE THREAD

**Issue by kavishdahekar** [rainlab/pages-plugin#441]
- OctoberCMS Build: 465
- RainLab Pages Plugin Version: 1.3.3
- PHP Version: 7.4.5

### Description:
When using a repeater groups with a large description, the dropdown that displays all the groups of the repeater cuts off the description and does not display it as a tooltip when hovering over it.

### Steps To Reproduce:
Create repeater with groups and add a field with a large description.
```
# File : static-layout.htm

{variable type="repeater" name="page_contents" tab="Page Contents" style="collapsed" prompt="Add New Item" groups="$/plugin/pagebuilder/config/page_builder_repeater.yaml"}{/variable}
```
```
# File : plugins/pagebuilder/config/page_builder_repeater.yaml

flexslider:
  name: Flex Slider
  description: This description is too long and will not be displayed completely to the user thus limiting its use. Content editor will not get complete description of what this field does.
  icon: icon-thumb-tack
```

Screenshot:
![image](https://user-images.githubusercontent.com/3937361/82678421-3439f700-9c67-11ea-8a0d-a1ef412c84b2.png)
