### ISSUE TITLE
Error A widget with class name 'formPage----ViewBagSections' has not been bound to the controller" on line 567 of /modules/backend/classes/Controller.php

### ISSUE THREAD

**Issue by ketihar** [rainlab/pages-plugin#478]
- OctoberCMS Build: v2.0.9
- RainLab Pages Plugin Version: v1.4.3
- PHP Version: v7.3

### Description:
After update to Octobercms v.2.0.9 i get error on Pages plugin when i try to edit or add a field with colorpicker type (using grouped repeaters method).

### Steps To Reproduce:
In your static layout call a repeater yaml with those fields

```
content:
    name: Content
    description: Content
    fields:
        section_content_title:
            label: Title
            type: text
        section_content_color:
            label: Color
            type: colorpicker
```
In your pages plugin create a new page and try to add more than one field items.
You will get:
"A widget with class name 'formPageedbb207e8b0632bb270f2cec699e7b2cViewBagSections' has not been bound to the controller" on line 567 of /.../.../.../modules/backend/classes/Controller.php"

![Screenshot_2](https://user-images.githubusercontent.com/6757833/115705970-d5e52f00-a375-11eb-8d24-726ce4a33fa3.png)

If you use a repeater yaml without colorpicker field everything is working properly. The problem occurs only with this type of field.
