### ISSUE TITLE
menuItem viewBag with wrong values

### ISSUE THREAD

**Issue by jBOKA** [rainlab/pages-plugin#92]
I'm using the staticMenu component and handle the construction of the menus in custom partials. Now I came across the issue, that the viewBag variables (like cssClass or isExternal) only have "0" (string) values.
Shouldn't the viewBag be filled with the content from the correponding `menu.yaml` by default?
The yaml files seems to be alright:
```yaml
name: 'Menu name'
items:
    -
        title: 'title1'
        nesting: ''
        type: url
        url: 'http://url2'
        code: ''
        reference: ''
        cmsPage: ''
        replace: ''
        viewBag:
            isExternal: '1'
            isHidden: '0'
            cssClass: ''
    -
        title: 'title2'
        nesting: ''
        type: url
        url: 'http://url1'
        code: ''
        reference: ''
        cmsPage: ''
        replace: ''
        viewBag:
            isExternal: '1'
            isHidden: '0'
            cssClass: test
    -

```
